
name: Build

on:
  push:
    branches:
    - workflow-selfhosted
    paths-ignore:
    - 'documentation/**'
    - 'design/**'

  pull_request:
    types: [ ready_for_review, review_requested ]
    paths-ignore:
    - 'documentation/**'
    - 'design/**'
    
jobs:
  test_ubuntu_latest_selfhosted:
    name: test build on ubuntu-latest_selfhosted
    runs-on: self-hosted
    steps:
    - name: Set environment variable
      run: echo "RUNNING_ON_GITHUB=1" >> $GITHUB_ENV      
    - uses: actions/checkout@v4      
    - name: do test install in case of merged pull request
      run: cd /home/githubrunnerdebian/_work/firewall-orchestrator/firewall-orchestrator && ansible-playbook -e force_install=true site.yml -K
      env:
        RUNNING_ON_GITHUB_ACTIONS: ${{ env.RUNNING_ON_GITHUB }}
